[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/griot-cloud/parcel"
rust-version = "1.88"

[workspace.dependencies]
cel = { version = "0.14.5", default-features = false, features = ["regex", "chrono"] }
datafusion = { version = "55.1.0", default-features = false }
datafusion-expr = "55.1.0"
datafusion-common = "55.1.0"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
yaml_serde = "0.10.7"
sha2 = "0.10"
hex = "0.4"
thiserror = "2"
regex-syntax = "0.8"
